### ISSUE TITLE
Flathub Verification

### ISSUE THREAD

**Issue by sr66139p** [ikolomiko/ikooskar-qt#35]
I can tell by issue #24 that the Flathub version is the official package for Linux, but it shows up as Unverified on Flathub. Could you follow the Flathub documentation here https://docs.flathub.org/docs/for-app-authors/verification to verify the flatpak so that people know it's official?

**Comment by ikolomiko** [comment]
Thank you for the attention, I'd love to verify my app. However, due to TLD restrictions in Flathub infrastructure, I'm not able to do that.
The official domain of this application is `ikooskar.com.tr` and the app id is `tr.com.ikooskar.ikoOSKAR`. The verification system of Flathub detects my full domain as a subdomain and requires me to upload a file into `https://com.tr/<path>` which is obviously out of my reach. There's an open issue [here](https://github.com/flathub/flathub/issues/4943) and a [pull request](https://github.com/flathub-infra/website/pull/2301) to solve it, which has been on hold for quite some time.
As soon as this problem gets fixed, I'll be able to verify my app :)

**Comment by ikolomiko** [comment]
Required support for country-specific TLDs have been added to Flathub infra and now I have successfully verified my app!
